name: Alpine (standard)

images:
  # Alpine + Hugo
  alpine:
    target: alpine
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-alpine
    tests:
      - hugo

  # Alpine + Hugo + Asciidoctor
  asciidoctor:
    target: asciidoctor
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - "$(VERSION)-asciidoctor"
    tests:
      - hugo
      - asciidoctor

  # Alpine + Hugo + Pandoc
  pandoc:
    target: pandoc
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-pandoc
    tests:
      - hugo
      - pandoc

tests:
  hugo:
    command: version
    expected: hugo

  asciidoctor:
    entrypoint: asciidoctor
    command: --version
    expected: Asciidoctor 2

  pandoc:
    entrypoint: pandoc
    command: --version
    expected: Compiled with pandoc
