name: Alpine (extended)

images:
  # Alpine + Hugo extended
  ext-alpine:
    target: ext-alpine
    edge: true
    alias:
      - $(VERSION)-ext-alpine
    tests:
      - hugo
      - golang
      - node
      - yarn
      - postcss
    platforms:
      - linux/amd64


  # Alpine + Hugo extended + Asciidoctor
  ext-asciidoctor:
    target: ext-asciidoctor
    alias:
      - $(VERSION)-ext-asciidoctor
    tests:
      - hugo
      - asciidoctor
      - golang
      - node
      - yarn
      - postcss
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Pandoc
  ext-pandoc:
    target: ext-pandoc
    alias:
      - $(VERSION)-ext-pandoc
    tests:
      - hugo
      - pandoc
      - golang
      - node
      - yarn
      - postcss
      - rst2html
    platforms:
      - linux/amd64

tests:
  hugo:
    entrypoint: hugo
    command: version
    expected: hugo

  node:
    entrypoint: node
    command: --version

  asciidoctor:
    entrypoint: asciidoctor
    command: --version
    expected: Asciidoctor 2

  pandoc:
    entrypoint: pandoc
    command: --version
    expected: Compiled with pandoc

  golang:
    entrypoint: go
    command: version
    expected: go version

  yarn:
    entrypoint: yarn
    command: --version

  postcss:
    entrypoint: postcss
    command: --version

  rst2html:
    entrypoint: rst2html.py
    command: --version