name: Busybox (standard)

images:
  # Busybox + Hugo
  busybox:
    target: busybox
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - latest
      - $(VERSION)
      - $(VERSION)-busybox
    tests:
      - hugo

tests:
  hugo:
    command: version
    expected: hugo
