name: Debian (standard)

images:
  # Debian + Hugo
  debian:
    target: debian
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-debian
    tests:
      - hugo

tests:
  hugo:
    command: version
    expected: hugo
