name: Ubuntu (standard)

images:
  # Ubuntu + Hugo
  ubuntu:
    target: ubuntu
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-ubuntu
    tests:
      - hugo

tests:
  hugo:
    command: version
    expected: hugo
